name: Deploy to Firebase

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    paths:
     - "dist/quranethiopia/browser"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ethio-quran-75da0
